backend:
  name: git-gateway
  repo: naheller/gamepad-news
  branch: style-v4
  squash_merges: true

publish_mode: editorial_workflow

media_folder: 'static/img/uploads'
public_folder: '/img/uploads'

display_url: https://gamepad.news

collections:
  - name: 'blog'
    label: 'Gamepad News'
    title: 'Gamepad News'
    label_singular: 'Post'
    folder: 'src/pages/posts'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}-x'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string', default: '', required: false }
      - { label: 'Date', name: 'date', widget: 'date' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Description (150 chars max)', name: 'description', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: [] }
      - { label: 'Image file', name: 's3Image', widget: 'string' }
      - { label: 'Slug (do not change)', name: 'slugPartial', widget: 'string' }