backend:
  name: git-gateway
  repo: naheller/gamepad-news
  branch: master
  squash_merges: true

publish_mode: editorial_workflow
display_url: https://gamepad.news

media_library:
  name: uploadcare
  config:
    publicKey: dafe69442ae284f9a25b

collections:
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    description: 'Articles on Gamepad News'
    folder: 'src/pages/posts'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', pattern: ['^.{0,75}$', '75 chars max'] }
      - { label: 'Subtitle (optional)', name: 'subtitle', widget: 'string', default: '', required: false, pattern: ['^.{0,85}$', '85 chars max'] }
      - { label: 'Date (do not change)', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Meta Title', name: 'metaTitle', widget: 'string', pattern: ['^.{0,45}$', '45 chars max'] }
      - { label: 'Meta Description', name: 'metaDescription', widget: 'string', pattern: ['^.{0,150}$', '150 chars max'] }
      - { label: 'Tags', name: 'tags', widget: 'list', default: [] }
      - { label: 'Slug (do not change)', name: 'slugPartial', widget: 'string' }